### ISSUE TITLE
Subtraction method performs addition instead of subtraction

### ISSUE THREAD

**Issue by 3bdop** [abood1509/infs3203-group5#2]
**Steps to produce the bug:**
    1- Run the python file
    2- Put the inputs (two numbers)
    3- Choose the operation

**Expected Results:**
This method should subtract the two numbers from each other

**Actual Result:**
The method is adding the two numbers **not subtracting**

`def subtract(self, x, y):
        return x + y`

**Comment by L60102291** [comment]
its supposed to subtract therefore we changed the plus to a minus in the function.
def subtract(self, x, y):
return x - y

**Comment by 3bdop** [comment]
The issue is solved successfully.
